"""initial_schema

Revision ID: b65776dded38
Revises: 
Create Date: 2026-03-30 21:22:35.482296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b65776dded38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'REVIEW', 'COMPLETE', 'FAILED', name='ingest_status'), nullable=False),
    sa.Column('image_dir', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('HELLOFRESH', 'MANUAL', 'IMPORTED', name='ingest_source_type'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('category', sa.Enum('PRODUCE', 'DAIRY', 'MEAT', 'FISH', 'PANTRY', 'SPICE', 'BAKERY', 'OTHER', name='ingredient_category'), nullable=False),
    sa.Column('dimension', sa.Enum('MASS', 'VOLUME', 'COUNT', 'PACK', name='ingredient_dimension'), nullable=False),
    sa.Column('typical_unit', sa.Text(), nullable=False),
    sa.Column('count_to_mass_g', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('meal_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start')
    )
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('hero_image_path', sa.Text(), nullable=True),
    sa.Column('hello_fresh_style', sa.SmallInteger(), nullable=True),
    sa.Column('cooking_time_mins', sa.SmallInteger(), nullable=True),
    sa.Column('base_servings', sa.SmallInteger(), nullable=False),
    sa.Column('source_type', sa.Enum('HELLOFRESH', 'MANUAL', 'IMPORTED', name='source_type'), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('mood_tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_conversions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_unit', sa.Text(), nullable=False),
    sa.Column('to_unit', sa.Text(), nullable=False),
    sa.Column('factor', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_unit', 'to_unit', name='uq_unit_conversion')
    )
    op.create_table('cooking_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('current_step', sa.SmallInteger(), nullable=False),
    sa.Column('completed_steps', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('timers', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_substitutes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('substitute_ingredient_id', sa.UUID(), nullable=False),
    sa.Column('equivalence_note', sa.Text(), nullable=True),
    sa.Column('penalty_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substitute_ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingest_job_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('raw_llm_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parsed_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_corrected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now() + interval '90 days'"), nullable=False),
    sa.ForeignKeyConstraint(['ingest_job_id'], ['ingest_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pantry_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('last_confirmed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('decay_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('normalized_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('normalized_unit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timer_seconds', sa.Integer(), nullable=True),
    sa.Column('image_crop_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pantry_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pantry_item_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('reserved_for', sa.Enum('PLAN', 'ACTIVE_COOK', name='reservation_type'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pantry_item_id'], ['pantry_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pantry_reservations')
    op.drop_table('steps')
    op.drop_table('recipe_ingredients')
    op.drop_table('pantry_items')
    op.drop_table('meal_plan_entries')
    op.drop_table('llm_outputs')
    op.drop_table('ingredient_substitutes')
    op.drop_table('cooking_sessions')
    op.drop_table('unit_conversions')
    op.drop_table('recipes')
    op.drop_table('meal_plans')
    op.drop_table('ingredients')
    op.drop_table('ingest_jobs')
    # ### end Alembic commands ###
